### ISSUE TITLE
[Request] adjustable reactive power

### ISSUE THREAD

**Issue by DarkSummit** [tbnobody/OpenDTU#1369] opened 2023-09-22 13:47 UTC
### Is your feature request related to a problem? Please describe.

According to my local grid operator I have to make an adjustment of the reactive power.
The default value for the Hoymiles is 1.0, I have to set 0.9 here.

### Describe the solution you'd like

Please add the option to set the reactive power.
How it is possible with the DTU Pro

**Comment by tbnobody** [comment] 2023-09-22 14:53
duplicate of #900
If you really have to change the profile you should contact your reseller. It's not event sure that the grid profile save method can somehow be reverse engineered or implemented.

**Closed by tbnobody** 2023-09-22 14:53 UTC
Labels: enhancement

**Comment by Fyr42** [comment] 2024-02-27 02:32
I found this document.  Just before the "4 - Conclusion" the picture mention the need of DTU Pro or Pro-S to access to the profile and modify it. The web interface is the vendor one "O&M" 

https://www.hoymiles.com/wp-content/uploads/2023/01/Technical-Note-Output-Power-Parameter-Interpretation-and-Control-Instructions-for-Hoymiles-Microinverter_REV1.1.pdf
