### ISSUE TITLE
[Request] Support for Alphanumeric serial numbers for inverter settings

### ISSUE THREAD

**Issue by evharten** [tbnobody/OpenDTU#1144] opened 2023-07-14 06:36 UTC
### Is your feature request related to a problem? Please describe.

Currently only an integer is allowed as Inverter(DTU) serial number, however the DTU-S-Lite for instance has Alphanumeric characters in it, mine for instance is xxxxAxxxxAAB (where the x's are numbers)
If we would be able to set the inverter(DTU) serialnumber to the same, we could perhaps co-exist, eg use the DTU-S-Lite together with OpenDTU, this gives options to update the inverters when needed.

### Describe the solution you'd like

Change the Inverter(DTU) settings to be an char(alphanumeric) field, instead of an int(integer) field.

**Comment by tbnobody** [comment] 2023-07-14 07:09
Duplicate of #714

**Closed by tbnobody** 2023-07-14 07:09 UTC
Labels: enhancement
