### ISSUE TITLE
Loosing Connection after few minutes after restart HMS-1600-4T

### ISSUE THREAD

**Issue by MLG1087** [tbnobody/OpenDTU#1961] opened 2024-05-04 11:05 UTC
### What happened?

The OpenDTU (build by selbstbau-pv.de) is loosing the connection after a few minutes of restart of the HMS-1600-4T. But restarting the HMS-1600-4T or setting a manual limit of watt producing is possible. The HMS-1600-4T in the openDTU Webinterface is shown as red and the delivery of data is not working anymore as long as the next restart.

### To Reproduce Bug

The OpenDTU (build by selbstbau-pv.de) is loosing the connection after a few minutes of restart of the HMS-1600-4T. But restarting the HMS-1600-4T or setting a manual limit of watt producing is possible. The HMS-1600-4T in the openDTU Webinterface is shown as red and the delivery of data is not working anymore as long as the next restart.

### Expected Behavior

i am expecting the deleivery of the data

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v24.4.24

### Relevant log/trace output

```Shell
RX Period End
13:01:06.595 > All missing
13:01:06.595 > Nothing received, resend whole request
13:01:06.595 > TX RealTimeRunData 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 0B 00 66 36 15 73 00 00 00 00 00 00 00 00 7D A8 1A 
13:01:07.107 > RX Period End
13:01:07.107 > All missing
13:01:07.107 > Nothing received, resend count exeeded
13:01:07.218 > TX SystemConfigPara 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 05 00 66 36 15 73 00 00 00 00 00 00 00 00 B3 A7 D5 
13:01:07.369 > RX Period End
13:01:07.369 > All missing
13:01:07.369 > Nothing received, resend whole request
13:01:07.369 > TX SystemConfigPara 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 05 00 66 36 15 73 00 00 00 00 00 00 00 00 B3 A7 D5 
13:01:07.624 > RX Period End
13:01:07.624 > All missing
13:01:07.624 > Nothing received, resend whole request
13:01:07.624 > TX SystemConfigPara 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 05 00 66 36 15 73 00 00 00 00 00 00 00 00 B3 A7 D5 
13:01:07.926 > RX Period End
13:01:07.926 > All missing
13:01:07.926 > Nothing received, resend whole request
13:01:07.926 > TX SystemConfigPara 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 05 00 66 36 15 73 00 00 00 00 00 00 00 00 B3 A7 D5 
13:01:08.236 > RX Period End
13:01:08.236 > All missing
13:01:08.236 > Nothing received, resend whole request
13:01:08.236 > TX SystemConfigPara 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 05 00 66 36 15 73 00 00 00 00 00 00 00 00 B3 A7 D5 
13:01:08.343 > RX Period End
13:01:08.343 > All missing
13:01:08.343 > Nothing received, resend count exeeded
13:01:09.154 > Fetch inverter: 116493520568
13:01:09.154 > Request SystemConfigPara
13:01:09.267 > TX ChannelChangeCommand 868.00 MHz --> 56 93 52 05 68 80 15 76 28 02 15 21 14 14 07 
13:01:09.370 > RX Period End
13:01:09.370 > All missing
13:01:09.370 > Nothing received, resend whole request
13:01:09.370 > TX ChannelChangeCommand 868.00 MHz --> 56 93 52 05 68 80 15 76 28 02 15 21 14 14 07 
13:01:09.425 > RX Period End
13:01:09.425 > All missing
13:01:09.425 > Nothing received, resend whole request
13:01:09.425 > TX ChannelChangeCommand 868.00 MHz --> 56 93 52 05 68 80 15 76 28 02 15 21 14 14 07 
13:01:09.472 > RX Period End
13:01:09.472 > All missing
13:01:09.472 > Nothing received, resend whole request
13:01:09.472 > TX ChannelChangeCommand 868.00 MHz --> 56 93 52 05 68 80 15 76 28 02 15 21 14 14 07 
13:01:09.521 > RX Period End
13:01:09.521 > All missing
13:01:09.521 > Nothing received, resend whole request
13:01:09.521 > TX ChannelChangeCommand 868.00 MHz --> 56 93 52 05 68 80 15 76 28 02 15 21 14 14 07 
13:01:09.578 > RX Period End
13:01:09.578 > All missing
13:01:09.578 > Nothing received, resend count exeeded
13:01:09.677 > TX RealTimeRunData 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 0B 00 66 36 15 78 00 00 00 00 00 00 00 00 4D DB 52 
13:01:09.897 > RX Period End
13:01:09.897 > All missing
13:01:09.897 > Nothing received, resend whole request
13:01:09.897 > TX RealTimeRunData 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 0B 00 66 36 15 78 00 00 00 00 00 00 00 00 4D DB 52 
13:01:10.486 > RX Period End
13:01:10.486 > All missing
13:01:10.486 > Nothing received, resend whole request
13:01:10.486 > TX RealTimeRunData 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 0B 00 66 36 15 78 00 00 00 00 00 00 00 00 4D DB 52 
13:01:11.101 > RX Period End
13:01:11.101 > All missing
13:01:11.101 > Nothing received, resend whole request
13:01:11.101 > TX RealTimeRunData 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 0B 00 66 36 15 78 00 00 00 00 00 00 00 00 4D DB 52 
13:01:11.613 > RX Period End
13:01:11.613 > All missing
13:01:11.613 > Nothing received, resend whole request
13:01:11.613 > TX RealTimeRunData 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 0B 00 66 36 15 78 00 00 00 00 00 00 00 00 4D DB 52 
13:01:12.125 > RX Period End
13:01:12.125 > All missing
13:01:12.125 > Nothing received, resend count exeeded
13:01:12.234 > TX SystemConfigPara 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 05 00 66 36 15 78 00 00 00 00 00 00 00 00 83 D4 9D 
13:01:12.378 > RX Period End
13:01:12.378 > All missing
13:01:12.378 > Nothing received, resend whole request
13:01:12.378 > TX SystemConfigPara 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 05 00 66 36 15 78 00 00 00 00 00 00 00 00 83 D4 9D 
13:01:12.739 > RX Period End
13:01:12.739 > All missing
13:01:12.739 > Nothing received, resend whole request
13:01:12.739 > TX SystemConfigPara 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 05 00 66 36 15 78 00 00 00 00 00 00 00 00 83 D4 9D 
13:01:12.944 > RX Period End
13:01:12.944 > All missing
13:01:12.944 > Nothing received, resend whole request
13:01:12.944 > TX SystemConfigPara 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 05 00 66 36 15 78 00 00 00 00 00 00 00 00 83 D4 9D 
13:01:13.146 > RX Period End
13:01:13.146 > All missing
13:01:13.146 > Nothing received, resend whole request
13:01:13.146 > TX SystemConfigPara 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 05 00 66 36 15 78 00 00 00 00 00 00 00 00 83 D4 9D 
13:01:13.456 > RX Period End
13:01:13.456 > All missing
13:01:13.456 > Nothing received, resend count exeeded
13:01:14.070 > Fetch inverter: 116493520568
13:01:14.070 > Request SystemConfigPara
13:01:14.182 > TX ChannelChangeCommand 868.00 MHz --> 56 93 52 05 68 80 15 76 28 02 15 21 14 14 07 
13:01:14.235 > RX Period End
13:01:14.235 > All missing
13:01:14.235 > Nothing received, resend whole request
13:01:14.235 > TX ChannelChangeCommand 868.00 MHz --> 56 93 52 05 68 80 15 76 28 02 15 21 14 14 07 
13:01:14.286 > RX Period End
13:01:14.286 > All missing
13:01:14.286 > Nothing received, resend whole request
13:01:14.286 > TX ChannelChangeCommand 868.00 MHz --> 56 93 52 05 68 80 15 76 28 02 15 21 14 14 07 
13:01:14.339 > RX Period End
13:01:14.339 > All missing
13:01:14.339 > Nothing received, resend whole request
13:01:14.339 > TX ChannelChangeCommand 868.00 MHz --> 56 93 52 05 68 80 15 76 28 02 15 21 14 14 07 
13:01:14.489 > RX Period End
13:01:14.489 > All missing
13:01:14.489 > Nothing received, resend whole request
13:01:14.489 > TX ChannelChangeCommand 868.00 MHz --> 56 93 52 05 68 80 15 76 28 02 15 21 14 14 07 
13:01:14.541 > RX Period End
13:01:14.541 > All missing
13:01:14.541 > Nothing received, resend count exeeded
13:01:14.692 > TX RealTimeRunData 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 0B 00 66 36 15 7D 00 00 00 00 00 00 00 00 1D E4 38 
13:01:14.892 > RX Period End
13:01:14.892 > All missing
13:01:14.892 > Nothing received, resend whole request
13:01:14.892 > TX RealTimeRunData 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 0B 00 66 36 15 7D 00 00 00 00 00 00 00 00 1D E4 38 
13:01:15.504 > RX Period End
13:01:15.504 > All missing
13:01:15.504 > Nothing received, resend whole request
13:01:15.504 > TX RealTimeRunData 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 0B 00 66 36 15 7D 00 00 00 00 00 00 00 00 1D E4 38 
13:01:16.005 > RX Period End
13:01:16.005 > All missing
13:01:16.005 > Nothing received, resend whole request
13:01:16.005 > TX RealTimeRunData 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 0B 00 66 36 15 7D 00 00 00 00 00 00 00 00 1D E4 38 
13:01:16.631 > RX Period End
13:01:16.631 > All missing
13:01:16.631 > Nothing received, resend whole request
13:01:16.631 > TX RealTimeRunData 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 0B 00 66 36 15 7D 00 00 00 00 00 00 00 00 1D E4 38 
13:01:17.066 > RX Period End
13:01:17.066 > All missing
13:01:17.066 > Nothing received, resend count exeeded
13:01:17.125 > TX SystemConfigPara 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 05 00 66 36 15 7D 00 00 00 00 00 00 00 00 D3 EB F7 
13:01:17.450 > RX Period End
13:01:17.450 > All missing
13:01:17.450 > Nothing received, resend whole request
13:01:17.450 > TX SystemConfigPara 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 05 00 66 36 15 7D 00 00 00 00 00 00 00 00 D3 EB F7 
13:01:17.654 > RX Period End
13:01:17.654 > All missing
13:01:17.654 > Nothing received, resend whole request
13:01:17.654 > TX SystemConfigPara 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 05 00 66 36 15 7D 00 00 00 00 00 00 00 00 D3 EB F7 
13:01:17.963 > RX Period End
13:01:17.963 > All missing
13:01:17.963 > Nothing received, resend whole request
13:01:17.963 > TX SystemConfigPara 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 05 00 66 36 15 7D 00 00 00 00 00 00 00 00 D3 EB F7 
13:01:18.166 > RX Period End
13:01:18.166 > All missing
13:01:18.166 > Nothing received, resend whole request
13:01:18.166 > TX SystemConfigPara 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 05 00 66 36 15 7D 00 00 00 00 00 00 00 00 D3 EB F7 
13:01:18.343 > RX Period End
13:01:18.343 > All missing
13:01:18.343 > Nothing received, resend count exeeded
13:01:19.088 > Fetch inverter: 116493520568
13:01:19.088 > Request SystemConfigPara
13:01:19.200 > TX ChannelChangeCommand 868.00 MHz --> 56 93 52 05 68 80 15 76 28 02 15 21 14 14 07 
13:01:19.304 > RX Period End
13:01:19.304 > All missing
13:01:19.304 > Nothing received, resend whole request
13:01:19.304 > TX ChannelChangeCommand 868.00 MHz --> 56 93 52 05 68 80 15 76 28 02 15 21 14 14 07 
13:01:19.353 > RX Period End
13:01:19.353 > All missing
13:01:19.353 > Nothing received, resend whole request
13:01:19.353 > TX ChannelChangeCommand 868.00 MHz --> 56 93 52 05 68 80 15 76 28 02 15 21 14 14 07 
13:01:19.403 > RX Period End
13:01:19.403 > All missing
13:01:19.403 > Nothing received, resend whole request
13:01:19.403 > TX ChannelChangeCommand 868.00 MHz --> 56 93 52 05 68 80 15 76 28 02 15 21 14 14 07 
13:01:19.454 > RX Period End
13:01:19.454 > All missing
13:01:19.454 > Nothing received, resend whole request
13:01:19.454 > TX ChannelChangeCommand 868.00 MHz --> 56 93 52 05 68 80 15 76 28 02 15 21 14 14 07 
13:01:19.505 > RX Period End
13:01:19.505 > All missing
13:01:19.505 > Nothing received, resend count exeeded
13:01:19.554 > TX RealTimeRunData 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 0B 00 66 36 15 82 00 00 00 00 00 00 00 00 E9 A1 76 
13:01:19.905 > RX Period End
13:01:19.905 > All missing
13:01:19.905 > Nothing received, resend whole request
13:01:19.905 > TX RealTimeRunData 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 0B 00 66 36 15 82 00 00 00 00 00 00 00 00 E9 A1 76 
13:01:20.463 > RX Period End
13:01:20.463 > All missing
13:01:20.463 > Nothing received, resend whole request
13:01:20.463 > TX RealTimeRunData 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 0B 00 66 36 15 82 00 00 00 00 00 00 00 00 E9 A1 76 
13:01:21.017 > RX Period End
13:01:21.017 > All missing
13:01:21.017 > Nothing received, resend whole request
13:01:21.017 > TX RealTimeRunData 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 0B 00 66 36 15 82 00 00 00 00 00 00 00 00 E9 A1 76 
13:01:21.571 > RX Period End
13:01:21.571 > All missing
13:01:21.571 > Nothing received, resend whole request
13:01:21.571 > TX RealTimeRunData 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 0B 00 66 36 15 82 00 00 00 00 00 00 00 00 E9 A1 76 
13:01:22.077 > RX Period End
13:01:22.077 > All missing
13:01:22.077 > Nothing received, resend count exeeded
13:01:22.126 > TX SystemConfigPara 865.00 MHz --> 15 93 52 05 68 80 15 76 28 80 05 00 66 36 15 82 00 00 00 00 00 00 00 00 27 AE B9
```

**Comment by tbnobody** [comment] 2024-05-04 11:23
Duplicate of #1921

**Closed by tbnobody** 2024-05-04 11:23 UTC
Labels: bug
