### ISSUE TITLE
[Request] Add text field to WebUI (f.e. near serial number or name) where we can store comments about system

### ISSUE THREAD

**Issue by KurtPfeifle** [tbnobody/OpenDTU#2250] opened 2024-09-02 23:13 UTC
### Is your feature request related to a problem? Please describe.

I always get confused when I look at multiple micro inverters: "Which is which?"

### Describe the solution you'd like

Add text field to WebUI (f.e. near serial number or name) where we can store comments about system

**Comment by tbnobody** [comment] 2024-09-20 20:34
Duplicate of #806

**Closed by tbnobody** 2024-09-20 20:34 UTC
Labels: enhancement
