### ISSUE TITLE
[Request] Provide more information about the radio signal quality

### ISSUE THREAD

**Issue by ituri** [tbnobody/OpenDTU#889] opened 2023-05-06 08:28 UTC
### Is your feature request related to a problem? Please describe.

In my quest to find the perfect location for my OpenDTU, I'd like to see some additional information like you see in ahoyDTU. This would help me to place the unit correctly while keeping the transmit power to a minimum.

### Describe the solution you'd like

A solution similar to the one in ahoyDTU (c.f. screenshot below).
![image](https://user-images.githubusercontent.com/871297/236612821-bb4aba53-6547-48aa-8702-f841cfb60cbf.PNG)

**Comment by tbnobody** [comment] 2023-05-06 10:03
Duplicate of #661

**Closed by tbnobody** 2023-05-06 10:03 UTC
Labels: enhancement
