### ISSUE TITLE
No more mqtt - output after several weeks of non-stop traffic

### ISSUE THREAD

**Issue by dl7ata** [tbnobody/OpenDTU#965] opened 2023-05-27 05:41 UTC
### What happened?

After several weeks there were no more output via mqtt. Dashboard looks good with reliable figures, but mqtt stopped.
After soft restart via dashboard, everything started as expected.
Running Tasmota 12.4.0.1 

### To Reproduce Bug

Don't know, will watch every day.

### Expected Behavior

mqtt should send EVERY time data

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

bf05dc8

**Comment by tbnobody** [comment] 2023-05-27 08:56
What showed Info --> MQTT at this moment? Did it show that is was still connected or did it show disconnected?
What was the status of the LWT topic?

**Comment by dl7ata** [comment] 2023-05-28 08:35
_MQTT_ at this moment:  I did not look at the MQTT on dashboard
_What was the status of the LWT topic?_ They were the last messages with valid values from 17h

**Comment by tbnobody** [comment] 2023-05-31 18:09
> They were the last messages with valid values from 17h

You write "They"... But there is only one LWT topic. By default its `solar/status`
![image](https://github.com/tbnobody/OpenDTU/assets/1753222/7f9c3aa0-ca73-48db-b4b0-567945f54c03)

**Comment by MichaelEnders** [comment] 2023-06-01 06:11
I think  I have seen the same issue: After a few days no more MQTT messages are sent. "MQTT Information"->"Runime Summary"->"Connection Status" shows "not connected". After restart of OpenDTU the connection is established again and MQTT messages are received.

**Comment by tbnobody** [comment] 2023-06-03 09:33
Your version is from Mar 17 ... On Mar 27 I upgraded the MQTT Library from 1.4.1 to 1.4.2. 
This fixed a reconnect error: https://github.com/bertmelis/espMqttClient/releases/tag/v1.4.2

So therefor I would suggest that you are updating your firmware.

**Comment by dl7ata** [comment] 2023-06-03 18:50
I just updated to
_SDK-Version | v4.4.4
0.1.25
v23.6.1_

I'll let you know, if I got that issue again - thanks a lot!

**Comment by MichaelEnders** [comment] 2023-06-05 05:22
Also after updateing to latest sources including Mqtt library 1.4.2 the reconnect problem still occurs.

**Comment by hannesb** [comment] 2023-06-06 11:57
I have the same problem. Updated yesterday to the latest working, today no more Mqtt updates after around 8:00. Web interface works fine.

**Comment by tbnobody** [comment] 2023-06-06 13:14
> I have the same problem.

And what shows the connection status?
What is the status of the LWT topic?
What shows the serial console?

Just saying "it does not work" will not help because at my several test installations I cannot reproduce this even after a longer uptime.

**Comment by hannesb** [comment] 2023-06-06 13:20
I'm have no access to the system right not as i'm not at home. I'll provide more information next weekend.

**Comment by XuttuX** [comment] 2023-06-09 12:32
I have the same problem MQTT does not send any data anymore. I have to rebbot the DTU to send data again.

Please find attached the relevant information.

DTU Firmware version: v23.6.1
LWT-Topic: solar/ dtu/status

![MQTT_1](https://github.com/tbnobody/OpenDTU/assets/131710122/48b318eb-2fbc-4d22-85e9-9e60ea773d0f)
![MQTT_2](https://github.com/tbnobody/OpenDTU/assets/131710122/37d7d1dd-9222-4791-90fc-ed8bcbc7e79b)
![SYSinfo_1](https://github.com/tbnobody/OpenDTU/assets/131710122/e0f98923-541d-4978-9702-3299be97376c)
![SYSinfo_2](https://github.com/tbnobody/OpenDTU/assets/131710122/11123e84-b98e-437c-8a76-cb04899fed9d)

Konsoleoutpt:
```Fetch inverter: 114482998398
14:07:23.456 > TX RealTimeRunData 865.00 MHz --> 15 82 99 83 98 80 14 69 68 80 0B 00 64 83 15 FB 00 00 00 00 00 00 00 00 B2 10 A0 
14:07:23.659 > Interrupt received
14:07:23.865 > RX 865.00 MHz --> 95 82 99 83 98 80 14 69 68 01 00 01 01 3B 01 3B 03 FC 03 FB 0C 90 0C 88 00 01 1E | -88 dBm
14:07:24.070 > Interrupt received
14:07:24.275 > RX 865.00 MHz --> 95 82 99 83 98 80 14 69 68 02 08 D5 00 01 08 74 06 3C 06 4D 08 D3 13 87 17 C3 48 | -88 dBm
14:07:24.479 > Interrupt received
14:07:24.787 > RX 865.00 MHz --> 95 82 99 83 98 80 14 69 68 83 00 05 01 0D 03 E7 01 D9 00 01 FA D3 9E | -88 dBm
14:07:24.992 > RX Period End
14:07:24.992 > Success
14:07:28.477 > Fetch inverter: 114482998398
14:07:28.678 > TX RealTimeRunData 865.00 MHz --> 15 82 99 83 98 80 14 69 68 80 0B 00 64 83 16 00 00 00 00 00 00 00 00 00 89 97 E4 
14:07:28.883 > Interrupt received
14:07:29.087 > Frame kaputt
14:07:29.292 > Interrupt received
14:07:29.497 > RX 865.00 MHz --> 95 82 99 83 98 80 14 69 68 02 08 D5 00 01 08 74 06 3C 06 4D 08 D2 13 87 17 E2 68 | -95 dBm
14:07:29.701 > Interrupt received
14:07:29.813 > Frame kaputt
14:07:29.820 > RX Period End
14:07:29.820 > Last missing
14:07:29.820 > Request retransmit: 3
14:07:29.820 > TX RequestFrame 865.00 MHz --> 15 82 99 83 98 80 14 69 68 83 03 
14:07:29.826 > RX Period End
14:07:29.826 > Last missing
14:07:29.826 > Request retransmit: 3
14:07:29.826 > TX RequestFrame 865.00 MHz --> 15 82 99 83 98 80 14 69 68 83 03 
14:07:29.833 > RX Period End
14:07:29.833 > Last missing
14:07:29.833 > Request retransmit: 3
14:07:29.833 > TX RequestFrame 865.00 MHz --> 15 82 99 83 98 80 14 69 68 83 03 
14:07:29.838 > Interrupt received
14:07:29.845 > Frame kaputt
14:07:29.851 > RX Period End
14:07:29.851 > Last missing
14:07:29.851 > Request retransmit: 3
14:07:29.851 > TX RequestFrame 865.00 MHz --> 15 82 99 83 98 80 14 69 68 83 03 
14:07:29.857 > Interrupt received
14:07:29.864 > Frame kaputt
14:07:29.872 > RX Period End
14:07:29.872 > Last missing
14:07:29.872 > Request retransmit: 3
14:07:29.872 > TX RequestFrame 865.00 MHz --> 15 82 99 83 98 80 14 69 68 83 03 
14:07:29.883 > Interrupt received
14:07:29.892 > Frame kaputt
14:07:29.921 > RX Period End
14:07:29.921 > Last missing
14:07:29.921 > Retransmit timeout
14:07:33.184 > Fetch inverter: 114482998398
14:07:33.217 > TX RealTimeRunData 865.00 MHz --> 15 82 99 83 98 80 14 69 68 80 0B 00 64 83 16 05 00 00 00 00 00 00 00 00 D9 A8 8E 
14:07:33.264 > Interrupt received
14:07:33.272 > RX 865.00 MHz --> 95 82 99 83 98 80 14 69 68 01 00 01 01 3B 01 3B 04 02 04 00 0C A0 0C 9A 00 01 39 | -91 dBm
14:07:33.314 > Interrupt received
14:07:33.321 > RX 865.00 MHz --> 95 82 99 83 98 80 14 69 68 02 08 D5 00 01 08 75 06 3C 06 4E 08 D2 13 86 17 E4 6D | -90 dBm
14:07:33.361 > Interrupt received
14:07:33.379 > RX 865.00 MHz --> 95 82 99 83 98 80 14 69 68 83 00 05 01 0E 03 E7 01 D9 00 01 46 10 E2 | -90 dBm
14:07:33.798 > RX Period End
14:07:33.798 > Success
```

**Comment by tbnobody** [comment] 2023-06-09 12:46
Is this the output of the serial console or just the web console? (The web console does not show everything). The MQTT status shows "getrennt". That means that it is correctly detected. But I am missing a "Connecting to MQTT..." in your logs. This should occour every time if the connection is not established.

It also seems that you are only using  a CMT module. That means you  should disable the NRF module. 

Next strange thing is that you get these "Frame kaputt" messages. This should never happen in a production environment. During the development it only occoured with bad connections and other strange hardware issues or if two DTU's sent at the same frequency etc.

**Comment by XuttuX** [comment] 2023-06-09 13:01
This is only the web console output. I have now updated to the newest version v23.6.9 and will see what happens tomorrow morning.

Yes I am only using the CMT module. Could you advise how to disable the NRF module? I have following pin-mapping:
```
[
    {
        "name": "Generic NodeMCU 38 pin with CMT2300A",
        "cmt": {
            "clk": 12,
            "cs": 27,
            "fcs": 26,
            "sdio": 14,
            "gpio2": -1,
            "gpio3": -1
        },
        "eth": {
            "enabled": false,
            "phy_addr": -1,
            "power": -1,
            "mdc": -1,
            "mdio": -1,
            "type": -1,
            "clk_mode": -1
        }
    }
]
```

Maybe I missed the correct setting somewhere.

**Comment by joba-1** [comment] 2023-06-19 09:17
I have the same problem.
Second time, with weeks in between.
Mqtt status says disconnected.
I rebooted the mqtt server ~4 days ago. Automatic reconnect was no problem then.
A save of unchanged mqtt settings reconnects. No reboot required.

**Comment by HeinKlocktein** [comment] 2023-06-26 18:03
Im letzten Bild vom FHEM Server sieht man schön das um 17.39 der OpenDTU (blaue Linie) das letzte MQTT Signal gesendet hat.
Ein anderes Gerät (esp8266, rote Linie) wird weiterhin empfangen.    
Speicher Button (auf der MQTT Konf. Seite) reicht aus, das es wieder geht. 
-->Neustart natürlich auch. 
  
[condole.txt](https://github.com/tbnobody/OpenDTU/files/11872214/condole.txt)
![1](https://github.com/tbnobody/OpenDTU/assets/61840781/3caf558c-874b-4914-88b5-7e1182b4ba90)
![2](https://github.com/tbnobody/OpenDTU/assets/61840781/e68522ac-abe2-4107-9289-7f5ecc2c88fc)
![3](https://github.com/tbnobody/OpenDTU/assets/61840781/45ccee41-0ffd-48d8-8cd8-0619c6ac8a65)
![4](https://github.com/tbnobody/OpenDTU/assets/61840781/398dc61d-06e8-4e7e-b250-76ea7546ec39)
![5](https://github.com/tbnobody/OpenDTU/assets/61840781/7489d4f0-8d1b-4d90-be4b-32ca339796f6)

**Comment by tbnobody** [comment] 2023-06-26 18:10
Good to know is that it is detecting it's disconnected state. In this moment you should see "Disconnected from MQTT. Disconnect reason: XXXXXX" in the konsole. For every reconnect attempt you should see ""Connecting to MQTT...""

**Comment by HeinKlocktein** [comment] 2023-06-26 18:21
So I have to wait and keep the console always on?

**Comment by tbnobody** [comment] 2023-06-26 18:26
To be honest, I don't know how to debug it otherwise. The best method would be if you could use the serial console (not the web konsole) as it would also show several critical runtime errors. But the program logic does a reconnect every time it receives a disconnect (which occours periodically if no connection can be established). I currently have no clue what happens in your case as the reconnect does not work. 

I checked several possibilities here (killing the broker, stopping the boker, just removing the network cable from the broker) and it reconnected without any issues.

**Comment by HeinKlocktein** [comment] 2023-06-26 19:18
I am not a professional so your help is very welcome. 
So I plugt it into the USB port, open Kitty (like Putty) and start the serial logging. 
Ok, the sun is down for today :-)

**Comment by tbnobody** [comment] 2023-07-03 21:07
Please see https://github.com/bertmelis/espMqttClient/issues/102

**Comment by dl7ata** [comment] 2023-07-12 18:49
I just compiled and updated with some trouble:
No live data. Looks like, that I am not able to configure the radio.

Device manager:
nRF24 Status | not configured

In tab DTU Settings is only "Serial" input
Tab device manager looks strange - no Param input possible:

![openDTU](https://github.com/tbnobody/OpenDTU/assets/12610562/78fbff33-4113-4eae-b935-d91bf8d3ad3f)

All other param looks good.
Any idea what went wrong?

**Comment by tbnobody** [comment] 2023-07-12 21:13
You used the generic_esp32 environment. This requires a Device Profile (See wiki).
You can also change the environment to generic (which is deprecated btw) and you can compile the source as you did previously

**Comment by dl7ata** [comment] 2023-07-13 05:22
I changed to _default_envs = generic_

> Compiling .pio/build/generic/src/WebApi_device.cpp.o
src/MqttHandleHass.cpp: In member function 'void MqttHandleHassClass::createDeviceInfo(ArduinoJson::V6212PB::JsonObject&, std::shared_ptr<InverterAbstract>)':
src/MqttHandleHass.cpp:264:20: error: 'AUTO_GIT_HASH' was not declared in this scope
     object["sw"] = AUTO_GIT_HASH;
                    ^~~~~~~~~~~~~
*** [.pio/build/generic/src/MqttHandleHass.cpp.o] Error 1


Any other place to change configuration for ESP32?

**Comment by tbnobody** [comment] 2023-07-17 19:38
Going to close this issue asa from my standpoint it should be fixed. Feel free to reopen or open a new one.

**Closed by tbnobody** 2023-07-17 19:38 UTC
Labels: bug
