### ISSUE TITLE
[Request] Adding Modbus TCP to the repository

### ISSUE THREAD

**Issue by ArekKubacki** [tbnobody/OpenDTU#1146] opened 2023-07-15 07:31 UTC
### Describe the solution you'd like

My solution for adding Modbus to the repository is added in the pull request. Several users are willing to be added to the main repository. Any chance to add it?

**Comment by tbnobody** [comment] 2023-07-15 08:38
duplicate of #553 

Will have a look at the source if there is time.

**Closed by tbnobody** 2023-07-15 08:38 UTC
Labels: enhancement
