### ISSUE TITLE
[Request] Implement multiple wifi configs

### ISSUE THREAD

**Issue by CommanderRedYT** [tbnobody/OpenDTU#1667] opened 2024-01-18 20:00 UTC
### Describe the solution you'd like

I would like one or two more slots for wifis. The problem is that currently if one wifi ssid dies, it cannot switch to others that might be working.

**Comment by nkappler** [comment] 2024-01-27 12:48
duplicate of #66

**Closed** 2024-01-27 14:05 UTC
Labels: enhancement
