### ISSUE TITLE
Display  RSSI ISM Band

### ISSUE THREAD

**Issue by dg3feh** [tbnobody/OpenDTU#1882] opened 2024-04-02 12:57 UTC
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

It would be nice if the RSSI ISM band value is displayed in the General-table  on the LiveView site.

**Comment by tbnobody** [comment] 2024-04-02 13:42
Duplicate of #1856

**Closed by tbnobody** 2024-04-02 13:42 UTC
Labels: enhancement
