### ISSUE TITLE
half of API missing after update to v24.2.16

### ISSUE THREAD

**Issue by 7Netler** [tbnobody/OpenDTU#1763] opened 2024-02-18 13:32 UTC
### What happened?

After upgrade openDTU on ESP32 to v24.2.16 the API ist just basic and gives out a few values. 

### To Reproduce Bug

upgrade to v24.2.16

### Expected Behavior

rective the missing API values

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v24.2.16

**Comment by tbnobody** [comment] 2024-02-18 14:36
Thats not an issue. it is shown on the changelog as well as in the readme at the start page. This change reduces the memory allocation by factor 10-11 and provides a much more stable operation. 
This is also a duplicate of #1741 and more infos can be found in the git log (https://github.com/tbnobody/OpenDTU/commit/c27ecc3620f656fbdfaa7e9f0f3deca6a371a373)

**Closed by tbnobody** 2024-02-18 14:36 UTC
Labels: bug
