### ISSUE TITLE
[Request] switch off sending commands when there is no stable connection to inverter

### ISSUE THREAD

**Issue by 001oc** [tbnobody/OpenDTU#1478] opened 2023-11-05 19:38 UTC
### Is your feature request related to a problem? Please describe.

When over mqtt (or from whatever) power limiting commands are comming in to opendtu, while there is no stable connecting to inverter, there will no connection being established. If mqtt is switched off manually and opendtu is rebooted the connection is comming up quiet fast. After that it is no problem to switch on mqtt again, even with power limitting commands - which are executed after that too.

### Describe the solution you'd like

Even if it is working with some or most of the inverters without having to switch of power limmiting commands, at least some inverters have difficulties to start up at the morning under this conditions. As of that opendtu should check if there is a stable connection to the inverter. If there is no stable connection to the inverter, opendtu shouldn't send any commands expect commands needed to establish connection. As such commands can prevent establishing building up a stable connection to the inverter and it makes even no sence to send commands that can't be executed at all because there is no connection there should be a possibility to switch of (drop) such commands automatically when there is no connection ( inverter available && inveter not producing).

### Describe alternatives you've considered

Right now I solve the problem by checking availability and productivity of the inverter within nodered and stop sending such power limiting commands when the inverter is not reachable . As node red is fare away from the "problem" it should be solved as near as possilble from its roots ... at opendtu

**Comment by tbnobody** [comment] 2023-11-05 19:42
Duplicate of #1468

**Closed by tbnobody** 2023-11-05 19:42 UTC
Labels: enhancement
