### ISSUE TITLE
v23.11.15 needs reboot in the morning ,no data

### ISSUE THREAD

**Issue by DocSnyd3r** [tbnobody/OpenDTU#1507] opened 2023-11-17 07:33 UTC
### What happened?

Hi,
after updating to v23.11.15 I had to manually reboot yesterday and today.
The inverter started but it still showed all 0s. After reboot all was fine.
Maybe this has todo with the calculate day fix in v23.11.16? If so I already applied the update.

The Mqtt change for HA wokring fine in v23.11.15...

### To Reproduce Bug

flash v23.11.15 wait till next morning

### Expected Behavior

data visible in DTU

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

sorry-already-switched

**Comment by tbnobody** [comment] 2023-11-17 09:24
Duplicate of #1508

**Closed by tbnobody** 2023-11-17 09:24 UTC
Labels: bug
