### ISSUE TITLE
[Request]Alphanumeric serial number required but entry only possible numerically

### ISSUE THREAD

**Issue by d-blaue-Klaus** [tbnobody/OpenDTU#1994] opened 2024-05-19 07:42 UTC
### Is your feature request related to a problem? Please describe.

I have a new Hoymiles HMS-800-2T inverter and would like to add it to the system of my existing HMS inverters (mainly HMS-1800-4T). The inverter is equipped with an alpha numeric serial number. Because the input field only allows numerical numbers, I cannot add this to the open DTU setup (OpenDTU on Battery ... 2024.02.19.post1)

### Describe the solution you'd like

Input field not only allows numbers to be entered, but also letters

**Comment by tbnobody** [comment] 2024-05-19 08:52
Duplicate of #1989, #1972, #1926, #1904 etc.....

You are using an old version. Just upgrade. This was already implemented several weeks ago.

**Closed by tbnobody** 2024-05-19 08:52 UTC
Labels: enhancement
