### ISSUE TITLE
total current power via mqtt to HomeAssistant

### ISSUE THREAD

**Issue by AzraelsDisk** [tbnobody/OpenDTU#1907] opened 2024-04-12 11:47 UTC
### Is your feature request related to a problem? Please describe.

Today, I have to build an additional unit in the HA to combine all the current performance information from the individual devices into one.

### Describe the solution you'd like

I would like to see the current total power as it is available via MQTT under solar/ac/power in the Home Assistant automatically.

**Comment by tbnobody** [comment] 2024-04-12 11:56
Duplicate of #1050

**Closed by tbnobody** 2024-04-12 11:56 UTC
Labels: enhancement
